"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional



@dataclasses.dataclass
class AssetReportPdfGetResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    asset_report_pdf_get_response: Optional[bytes] = dataclasses.field(default=None)
    r"""A PDF of the Asset Report"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

