"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional



@dataclasses.dataclass
class IncomeVerificationDocumentsDownloadResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    income_verification_documents_download_200_application_zip_binary_string: Optional[bytes] = dataclasses.field(default=None)
    r"""A ZIP file containing source documents(s) used as the basis for income verification."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

