"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import watchlistscreeningindividualreviewcreateresponse as shared_watchlistscreeningindividualreviewcreateresponse
from typing import Optional


@dataclasses.dataclass
class WatchlistScreeningIndividualReviewCreateResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    watchlist_screening_individual_review_create_response: Optional[shared_watchlistscreeningindividualreviewcreateresponse.WatchlistScreeningIndividualReviewCreateResponse] = dataclasses.field(default=None)
    r"""OK"""
    

