"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import creditfilter as shared_creditfilter
from ..shared import depositoryfilter as shared_depositoryfilter
from ..shared import investmentfilter as shared_investmentfilter
from ..shared import loanfilter as shared_loanfilter
from dataclasses_json import Undefined, dataclass_json
from test_plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AccountFiltersResponse:
    r"""The `account_filters` specified in the original call to `/link/token/create`."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    credit: Optional[shared_creditfilter.CreditFilter] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('credit'), 'exclude': lambda f: f is None }})
    r"""A filter to apply to `credit`-type accounts"""
    depository: Optional[shared_depositoryfilter.DepositoryFilter] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('depository'), 'exclude': lambda f: f is None }})
    r"""A filter to apply to `depository`-type accounts"""
    investment: Optional[shared_investmentfilter.InvestmentFilter] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('investment'), 'exclude': lambda f: f is None }})
    r"""A filter to apply to `investment`-type accounts (or `brokerage`-type accounts for API versions 2018-05-22 and earlier)."""
    loan: Optional[shared_loanfilter.LoanFilter] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('loan'), 'exclude': lambda f: f is None }})
    r"""A filter to apply to `loan`-type accounts"""
    

