"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import creditfreddiemacreportinginformation_voa_2_4 as shared_creditfreddiemacreportinginformation_voa_2_4
from ..shared import creditfreddiemacverificationofassetresponse_voa_2_4 as shared_creditfreddiemacverificationofassetresponse_voa_2_4
from ..shared import serviceproductfulfillment as shared_serviceproductfulfillment
from dataclasses_json import Undefined, dataclass_json
from test_plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreditFreddieMacVerificationOfAssetVOA24:
    r"""Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""
    reporting_information: shared_creditfreddiemacreportinginformation_voa_2_4.CreditFreddieMacReportingInformationVOA24 = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('REPORTING_INFORMATION') }})
    r"""Information about an report identifier and a report name."""
    service_product_fulfillment: shared_serviceproductfulfillment.ServiceProductFulfillment = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('SERVICE_PRODUCT_FULFILLMENT') }})
    r"""A collection of details related to a fulfillment service or product in terms of request, process and result."""
    verification_of_asset_response: shared_creditfreddiemacverificationofassetresponse_voa_2_4.CreditFreddieMacVerificationOfAssetResponseVOA24 = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('VERIFICATION_OF_ASSET_RESPONSE') }})
    r"""Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

