"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import linksessionsuccessmetadata as shared_linksessionsuccessmetadata
from dataclasses_json import Undefined, dataclass_json
from test_plaid import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LinkSessionSuccess:
    r"""An object representing an [onSuccess](https://plaid.com/docs/link/web/#onsuccess) callback from Link."""
    metadata: Optional[shared_linksessionsuccessmetadata.LinkSessionSuccessMetadata] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metadata') }})
    r"""Displayed once a user has successfully linked their Item."""
    public_token: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('public_token') }})
    r"""Displayed once a user has successfully linked their Item."""
    

