"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import paymentamount as shared_paymentamount
from ..shared import paymentconsentperiodicalignment as shared_paymentconsentperiodicalignment
from ..shared import paymentconsentperiodicinterval as shared_paymentconsentperiodicinterval
from dataclasses_json import Undefined, dataclass_json
from test_plaid import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PaymentConsentPeriodicAmount:
    r"""Defines consent payments limitations per period."""
    alignment: shared_paymentconsentperiodicalignment.PaymentConsentPeriodicAlignment = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('alignment') }})
    r"""Where the payment consent period should start.

    `CALENDAR`: line up with a calendar.

    `CONSENT`: on the date of consent creation.
    """
    amount: shared_paymentamount.PaymentAmount = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount') }})
    r"""Maximum cumulative amount for all payments in the specified interval."""
    interval: shared_paymentconsentperiodicinterval.PaymentConsentPeriodicInterval = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('interval') }})
    r"""Payment consent periodic interval."""
    

