"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import roledetail as shared_roledetail
from dataclasses_json import Undefined, dataclass_json
from test_plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Role:
    r"""ADocumentation not found in the MISMO model viewer and not provided by Freddie Mac."""
    role_detail: shared_roledetail.RoleDetail = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ROLE_DETAIL') }})
    r"""Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

